<?php

namespace App\Console\Commands;

use App\Jobs\GenerateConceptJob;
use App\Models\ScheduledTask;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class ProcessScheduledTasks extends Command
{
    protected $signature = 'tasks:process';
    protected $description = 'Process scheduled tasks for auto content generation';

    public function handle(): int
    {
        $this->info('Processing scheduled tasks...');

        $tasks = ScheduledTask::with('channel.user')
            ->where('is_active', true)
            ->where('next_run_at', '<=', now())
            ->get();

        $this->info("Found {$tasks->count()} tasks to process");

        foreach ($tasks as $task) {
            try {
                $this->processTask($task);
            } catch (\Exception $e) {
                Log::error('Failed to process scheduled task', [
                    'task_id' => $task->id,
                    'error' => $e->getMessage(),
                ]);
                $this->error("Failed to process task {$task->id}: {$e->getMessage()}");
            }
        }

        $this->info('Done processing scheduled tasks');

        return 0;
    }

    protected function processTask(ScheduledTask $task): void
    {
        $channel = $task->channel;
        $config = $task->config ?? [];

        if (!$channel || !$channel->user) {
            Log::warning('Scheduled task has no channel or user', ['task_id' => $task->id]);
            return;
        }

        $this->info("Processing task {$task->id} for channel {$channel->name}");

        // Create new project
        $project = $channel->projects()->create([
            'user_id' => $channel->user_id,
            'title' => $this->generateTitle($config),
            'description' => 'Auto-generated by scheduled task',
            'status' => 'processing',
        ]);

        $this->info("Created project {$project->id}");

        // Dispatch concept generation job
        GenerateConceptJob::dispatch($project->id, [
            'theme' => $config['theme'] ?? $channel->name,
            'duration' => $config['duration'] ?? 60,
            'audience' => $config['audience'] ?? 'general',
            'platform' => $config['platform'] ?? $channel->platform ?? 'YouTube',
            'language' => $config['language'] ?? 'English',
            'scene_count' => $config['scene_count'] ?? 4,
            'aspect_ratio' => $config['aspect_ratio'] ?? '16:9',
            'visual_style' => $config['visual_style'] ?? 'cinematic',
            'auto_generate' => true,
        ]);

        // Update task
        $task->update([
            'last_run_at' => now(),
            'next_run_at' => $this->calculateNextRun($task->cron_expression),
        ]);

        Log::info('Scheduled task processed successfully', [
            'task_id' => $task->id,
            'project_id' => $project->id,
        ]);
    }

    protected function generateTitle(array $config): string
    {
        $theme = $config['theme'] ?? 'Video';
        $date = now()->format('Y-m-d H:i');
        return "{$theme} - {$date}";
    }

    protected function calculateNextRun(string $cron): \DateTime
    {
        // Parse cron expression
        $parts = explode(' ', $cron);
        $now = new \DateTime();
        $next = clone $now;

        if (count($parts) >= 5) {
            $minute = $parts[0];
            $hour = $parts[1];
            $dayOfMonth = $parts[2];
            $month = $parts[3];
            $dayOfWeek = $parts[4];

            // Simple handling for common patterns
            if ($minute !== '*' && $hour !== '*') {
                // Specific time daily
                $next->setTime((int) $hour, (int) $minute, 0);
                if ($next <= $now) {
                    $next->modify('+1 day');
                }
            } elseif ($minute !== '*') {
                // Every hour at specific minute
                $next->setTime((int) $next->format('H'), (int) $minute, 0);
                if ($next <= $now) {
                    $next->modify('+1 hour');
                    $next->setTime((int) $next->format('H'), (int) $minute, 0);
                }
            } else {
                // Default: next hour
                $next->modify('+1 hour');
                $next->setTime((int) $next->format('H'), 0, 0);
            }
        } else {
            // Default: next hour
            $next->modify('+1 hour');
        }

        return $next;
    }
}
